import type { Metadata } from "next";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Privacy Policy - Staycio",
  description: "How Staycio collects, uses, and protects your information.",
};

const LAST_UPDATED = "July 12, 2026";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-black text-white flex flex-col">
      <Header />
      <main className="flex-1">
        <div className="mx-auto max-w-3xl px-6 py-16">
          <h1 className="text-3xl lg:text-4xl font-semibold tracking-tight">
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-zinc-500">
            Last updated: {LAST_UPDATED}
          </p>

          <div className="mt-10 space-y-10 text-sm leading-relaxed text-zinc-400 [&_h2]:text-lg [&_h2]:font-medium [&_h2]:text-white [&_ul]:mt-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_p]:mt-3">
            <section>
              <h2>1. Information we collect</h2>
              <p>
                When you use Staycio, we collect information you provide
                directly and information generated by your use of the service:
              </p>
              <ul>
                <li>
                  <span className="text-zinc-300">Account information</span> —
                  name, email address, and phone number when you create an
                  account or submit a tour request.
                </li>
                <li>
                  <span className="text-zinc-300">Search activity</span> —
                  searches, filters, favorites, saved searches, and buildings
                  you view, used to power alerts and recommendations.
                </li>
                <li>
                  <span className="text-zinc-300">Conversations</span> —
                  messages you exchange with our AI assistants (chat, voice,
                  and video avatar), used to answer your questions and, with
                  your consent, to connect you with a leasing team.
                </li>
                <li>
                  <span className="text-zinc-300">Usage data</span> — pages
                  visited, device and browser type, and approximate location
                  derived from IP address, used for analytics and security.
                </li>
              </ul>
            </section>

            <section>
              <h2>2. How we use your information</h2>
              <ul>
                <li>Provide and improve apartment search and discovery.</li>
                <li>
                  Send tour confirmations, saved-search alerts, and service
                  emails you request. Marketing email is opt-in and every
                  message includes an unsubscribe link.
                </li>
                <li>
                  Route your inquiries to licensed agents, building partners,
                  or certified tour guides when you request a showing.
                </li>
                <li>Detect abuse and keep the platform secure.</li>
              </ul>
            </section>

            <section>
              <h2>3. How we share information</h2>
              <p>
                We do not sell your personal information. We share it only
                with:
              </p>
              <ul>
                <li>
                  Buildings, brokerages, agents, and certified tour guides —
                  when you request a tour or ask to be contacted about a
                  specific property.
                </li>
                <li>
                  Service providers that operate our platform — hosting,
                  database and authentication, email delivery, mapping, and AI
                  processing — bound by their own confidentiality obligations.
                </li>
                <li>
                  Authorities, when required by law or to protect the safety
                  of our users.
                </li>
              </ul>
            </section>

            <section>
              <h2>4. AI features</h2>
              <p>
                Conversations with our AI assistants are processed by
                third-party AI providers to generate responses. Do not share
                sensitive personal information (such as government IDs or
                financial account numbers) in chat or voice conversations.
              </p>
            </section>

            <section>
              <h2>5. Data retention &amp; your choices</h2>
              <ul>
                <li>
                  You can update or delete your profile information from your
                  account page at any time.
                </li>
                <li>
                  You can unsubscribe from alerts in the email footer or from
                  your account settings.
                </li>
                <li>
                  To request deletion of your account and associated data,
                  contact us at the address below.
                </li>
              </ul>
            </section>

            <section>
              <h2>6. Security</h2>
              <p>
                We use industry-standard safeguards, including encrypted
                connections, role-based access controls, and row-level
                database security. No method of transmission or storage is
                100% secure, and we cannot guarantee absolute security.
              </p>
            </section>

            <section>
              <h2>7. Children</h2>
              <p>
                Staycio is not directed to individuals under 18, and we do not
                knowingly collect information from them.
              </p>
            </section>

            <section>
              <h2>8. Changes &amp; contact</h2>
              <p>
                We may update this policy from time to time; material changes
                will be reflected by the date above. Questions or requests:{" "}
                <a
                  href="mailto:hello@staycio.com"
                  className="text-white underline underline-offset-4 hover:text-zinc-300"
                >
                  hello@staycio.com
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
